# workflow for the django_testing app

name: Tutorials App Pipeline

# Set up how the workflow is configured/triggered
on:
  
  # Triggers the workflow on push or pull request events ( but only for the "main" branch )
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set up the Job for this workflow
jobs:
  
  # This workflow contains a single job - named "build-and-test"
  build-and-test:
    
    # The runner environment (VM) to use
    runs-on: ubuntu-latest

    # Steps mostly contain CLI commands (via "run") and actions (via "uses")
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # NOTE: dig deeper into github's evironment variables 
      # You can optionally provide a name before a step. This is an example of an unnamed step.
      - uses: actions/checkout@v2

      # Runs a single echo command using the runners shell
      - run: echo Entering Django CI/CD Pipeline

      # Uses the action setup-python@v2, specifying v3.9
      # This installs Python 3.9 to the runner environment
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9
          
      # Runs a set of commands to install dependencies in the runner environment
      # NOTE: | pipe allows mutiple CLI commands to be issued 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        
      # Runs database migrations on the Django app
      - name: Run migrations
        run: python manage.py migrate
        
      # Run all tests with verbose flag
      - name: Run all test
        run: pytest -v
        
          
          
